version: "2"

services:
   jenkins:
    build: jenkins/.
    volumes:
      - /var/jenkins_home
      - /tmp
      - /var/jenkins_home/keys
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins
    environment:
#   example labels:
    labels:
      com.example.description: "Accounting webapp"
      com.example.department: "Finance"
      com.example.label-with-empty-value: ""
